name: RecipeApp
options:
  bundleIdPrefix: io.sammons
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  RecipeApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/RecipeApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.sammons.feedmeplanner
        DEVELOPMENT_TEAM: 4NV3FL9B87
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "FeedMe Distribution"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_CFBundleDisplayName: "Feed Me: Meal Planner"
        INFOPLIST_KEY_NSHumanReadableCopyright: "© 2026 Sammons Software LLC"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  RecipeAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/RecipeAppTests
    dependencies:
      - target: RecipeApp
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RecipeApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RecipeApp"
  RecipeAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/RecipeAppUITests
    dependencies:
      - target: RecipeApp
    settings:
      base:
        TEST_TARGET_NAME: RecipeApp
schemes:
  RecipeApp:
    build:
      targets:
        RecipeApp: all
        RecipeAppTests: [testing]
        RecipeAppUITests: [testing]
    test:
      targets:
        - RecipeAppTests
        - RecipeAppUITests
