import Foundation
import SwiftData
import Testing
@testable import RecipeApp

@Suite("FunctionalFlow", .serialized)
struct FunctionalFlowTests {
    @Test @MainActor func mealPlanToShoppingToCompletionFlow() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let flour = Ingredient(name: "flour", displayName: "Flour", category: IngredientCategory.grain)
        context.insert(flour)
        context.insert(InventoryItem(quantity: 200, unit: "g", ingredient: flour))

        let bread = Recipe(title: "Bread", servings: 2)
        context.insert(bread)
        context.insert(RecipeIngredient(quantity: 500, unit: "g", recipe: bread, ingredient: flour))

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 2, recipe: bread)
        context.insert(entry)
        try context.save()

        ShoppingListGenerator.generate(context: context, lookaheadDays: 3)

        let generatedBeforeCompletion = try context.fetch(
            FetchDescriptor<ShoppingListItem>(
                predicate: #Predicate { $0.isAutoGenerated && !$0.isChecked }
            )
        )
        #expect(generatedBeforeCompletion.count == 1)
        // 300 g flour (Grain) → purchase catalog: lb, 0.25 inc → 0.661 lb → snap 0.75 lb
        #expect(abs(generatedBeforeCompletion[0].quantity - 0.75) < 0.01)
        #expect(generatedBeforeCompletion[0].unit == "lb")

        MealCompletionService.markCompleted(entry, context: context)
        try context.save()

        #expect(entry.status == MealStatus.completed)
        let inventoryAfterCompletion = try context.fetch(FetchDescriptor<InventoryItem>())
        #expect(inventoryAfterCompletion.isEmpty)

        ShoppingListGenerator.generate(context: context, lookaheadDays: 3)
        let generatedAfterCompletion = try context.fetch(
            FetchDescriptor<ShoppingListItem>(
                predicate: #Predicate { $0.isAutoGenerated && !$0.isChecked }
            )
        )
        #expect(generatedAfterCompletion.isEmpty)
    }

    @Test @MainActor func overdueWindowAndDismissalFlow() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let recipe = Recipe(title: "Overdue Target")
        context.insert(recipe)

        let startOfToday = DateHelpers.startOfDay(Date())
        let yesterday = DateHelpers.addDays(-1, to: startOfToday)
        let fourDaysAgo = DateHelpers.addDays(-4, to: startOfToday)
        let tomorrow = DateHelpers.addDays(1, to: startOfToday)

        let overdue = MealPlanEntry(date: yesterday, mealSlot: MealSlot.lunch, servings: 1, recipe: recipe)
        let tooOld = MealPlanEntry(date: fourDaysAgo, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe)
        let future = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.breakfast, servings: 1, recipe: recipe)
        let alreadyCompleted = MealPlanEntry(
            date: yesterday, mealSlot: MealSlot.snack, servings: 1, status: MealStatus.completed, recipe: recipe)
        context.insert(overdue)
        context.insert(tooOld)
        context.insert(future)
        context.insert(alreadyCompleted)
        try context.save()

        let initialOverdue = MealCompletionService.overdueEntries(context: context)
        #expect(initialOverdue.count == 1)
        #expect(initialOverdue[0] === overdue)

        MealCompletionService.markSkipped(overdue)
        try context.save()

        let overdueAfterSkip = MealCompletionService.overdueEntries(context: context)
        #expect(overdueAfterSkip.isEmpty)
    }

    @Test @MainActor func lookaheadPreferenceDrivesPlanningResults() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "tomato", displayName: "Tomato", category: IngredientCategory.vegetable)
        context.insert(ingredient)

        let recipe = Recipe(title: "Tomato Soup", servings: 1)
        context.insert(recipe)
        context.insert(RecipeIngredient(quantity: 100, unit: "g", recipe: recipe, ingredient: ingredient))

        let nearEntry = MealPlanEntry(
            date: DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date())),
            mealSlot: MealSlot.lunch,
            servings: 1,
            recipe: recipe
        )
        let farEntry = MealPlanEntry(
            date: DateHelpers.addDays(5, to: DateHelpers.startOfDay(Date())),
            mealSlot: MealSlot.dinner,
            servings: 1,
            recipe: recipe
        )
        context.insert(nearEntry)
        context.insert(farEntry)
        context.insert(UserPreferences(shoppingLookaheadDays: 3))
        try context.save()

        let prefs = try context.fetch(FetchDescriptor<UserPreferences>())
        #expect(prefs.count == 1)

        ShoppingListGenerator.generate(context: context, lookaheadDays: prefs[0].shoppingLookaheadDays)
        var items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        // 100 g tomato (Vegetable) → purchase catalog: lb, 0.25 inc → 0.220 lb → snap 0.25 lb
        #expect(abs(items[0].quantity - 0.25) < 0.01)

        prefs[0].shoppingLookaheadDays = 7
        try context.save()

        ShoppingListGenerator.generate(context: context, lookaheadDays: prefs[0].shoppingLookaheadDays)
        items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        // 200 g tomato (Vegetable) → 0.441 lb → snap 0.5 lb
        #expect(abs(items[0].quantity - 0.5) < 0.01)
    }
}
