import Testing
import SwiftData
import Foundation
@testable import RecipeApp

@Suite("ShoppingListGenerator", .serialized)
struct ShoppingListGeneratorTests {
    @Test @MainActor func generatesItemsFromPlannedMeals() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "flour", displayName: "Flour", category: IngredientCategory.grain)
        context.insert(ingredient)

        let recipe = Recipe(title: "Bread", servings: 1)
        context.insert(recipe)

        let ri = RecipeIngredient(quantity: 500, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe)
        context.insert(entry)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        #expect(items[0].quantity == 500)
        #expect(items[0].unit == "g")
        #expect(items[0].isAutoGenerated == true)
    }

    @Test @MainActor func subtractsInventoryQuantities() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "flour")
        context.insert(ingredient)

        let recipe = Recipe(title: "Bread", servings: 1)
        context.insert(recipe)

        let ri = RecipeIngredient(quantity: 500, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        let inventory = InventoryItem(quantity: 200, unit: "g", ingredient: ingredient)
        context.insert(inventory)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe)
        context.insert(entry)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        #expect(items[0].quantity == 300) // 500 - 200
    }

    @Test @MainActor func servingMultiplierScalesQuantity() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "pasta")
        context.insert(ingredient)

        let recipe = Recipe(title: "Pasta", servings: 4)
        context.insert(recipe)

        let ri = RecipeIngredient(quantity: 400, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 2, recipe: recipe)
        context.insert(entry)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        #expect(items[0].quantity == 200) // 400 * (2/4)
    }

    @Test @MainActor func clearsAutoGeneratedUncheckedItems() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "rice")
        context.insert(ingredient)

        let existing = ShoppingListItem(
            quantity: 100, unit: "g",
            isChecked: false, isAutoGenerated: true,
            ingredient: ingredient
        )
        context.insert(existing)

        try context.save()

        // No meals planned — should clear existing and produce nothing
        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 0)
    }

    @Test @MainActor func ignoresCompletedAndSkippedMeals() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "chicken")
        context.insert(ingredient)

        let recipe = Recipe(title: "Chicken", servings: 1)
        context.insert(recipe)

        let ri = RecipeIngredient(quantity: 200, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))

        let completed = MealPlanEntry(
            date: tomorrow, mealSlot: MealSlot.lunch,
            servings: 1, status: MealStatus.completed, recipe: recipe
        )
        context.insert(completed)

        let skipped = MealPlanEntry(
            date: tomorrow, mealSlot: MealSlot.dinner,
            servings: 1, status: MealStatus.skipped, recipe: recipe
        )
        context.insert(skipped)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 0)
    }

    @Test @MainActor func ignoresMealsOutsideLookahead() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "beef")
        context.insert(ingredient)

        let recipe = Recipe(title: "Steak", servings: 1)
        context.insert(recipe)

        let ri = RecipeIngredient(quantity: 300, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        // 10 days from now, outside default 7-day lookahead
        let farFuture = DateHelpers.addDays(10, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: farFuture, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe)
        context.insert(entry)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 0)
    }

    @Test @MainActor func separatesItemsByUnit() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "tomatoes", displayName: "Tomatoes")
        context.insert(ingredient)

        let recipe1 = Recipe(title: "Salad", servings: 1)
        context.insert(recipe1)
        let ri1 = RecipeIngredient(quantity: 3, unit: "medium", recipe: recipe1, ingredient: ingredient)
        context.insert(ri1)

        let recipe2 = Recipe(title: "Sauce", servings: 1)
        context.insert(recipe2)
        let ri2 = RecipeIngredient(quantity: 400, unit: "g", recipe: recipe2, ingredient: ingredient)
        context.insert(ri2)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry1 = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.lunch, servings: 1, recipe: recipe1)
        context.insert(entry1)
        let entry2 = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe2)
        context.insert(entry2)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 2)
        let units = Set(items.map(\.unit))
        #expect(units == ["medium", "g"])
    }

    @Test @MainActor func inventoryDeductionMatchesUnit() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        let ingredient = Ingredient(name: "flour")
        context.insert(ingredient)

        let recipe = Recipe(title: "Bread", servings: 1)
        context.insert(recipe)
        let ri = RecipeIngredient(quantity: 500, unit: "g", recipe: recipe, ingredient: ingredient)
        context.insert(ri)

        // Inventory in cups — should NOT deduct from grams need
        let inventory = InventoryItem(quantity: 2, unit: "cups", ingredient: ingredient)
        context.insert(inventory)

        let tomorrow = DateHelpers.addDays(1, to: DateHelpers.startOfDay(Date()))
        let entry = MealPlanEntry(date: tomorrow, mealSlot: MealSlot.dinner, servings: 1, recipe: recipe)
        context.insert(entry)

        try context.save()

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 1)
        #expect(items[0].quantity == 500) // No deduction since units differ
        #expect(items[0].unit == "g")
    }

    @Test @MainActor func emptyMealPlanProducesNoItems() throws {
        let container = try makeTestContainer()
        let context = container.mainContext

        ShoppingListGenerator.generate(context: context)

        let items = try context.fetch(FetchDescriptor<ShoppingListItem>())
        #expect(items.count == 0)
    }
}
