name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build package
        run: swift build

      - name: Run xcodebuild first launch
        run: xcodebuild -runFirstLaunch || true

      - name: Build for iOS (xcodebuild)
        continue-on-error: true
        run: |
          xcodebuild \
            -scheme RecipeApp \
            -destination 'generic/platform=iOS Simulator' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            build
