name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REQUIRED_PLATFORMS: iOS

jobs:
  build:
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Ensure simulator runtimes
        run: |
          echo "=== Installed SDKs ==="
          xcodebuild -showsdks 2>/dev/null || true
          echo ""
          echo "=== Simulator Runtimes ==="
          xcrun simctl list runtimes 2>/dev/null || true
          echo ""
          for platform in $REQUIRED_PLATFORMS; do
            sdk_name=$(echo "$platform" | tr '[:upper:]' '[:lower:]')simulator
            if xcodebuild -showsdks 2>/dev/null | grep -q "$sdk_name"; then
              echo "$platform SDK available — skipping download"
            else
              echo "$platform SDK not found — downloading..."
              xcodebuild -downloadPlatform "$platform"
              echo "$platform download complete"
            fi
          done

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build package
        run: swift build

      - name: Build for iOS (xcodebuild)
        run: |
          xcodebuild \
            -scheme RecipeApp \
            -destination 'generic/platform=iOS Simulator' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            build
