name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REQUIRED_PLATFORMS: iOS

jobs:
  build:
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Ensure simulator runtimes
        run: |
          for platform in $REQUIRED_PLATFORMS; do
            if xcrun simctl list runtimes | grep -q "$platform"; then
              echo "$platform runtime already installed"
            else
              echo "$platform runtime missing — downloading..."
              xcodebuild -downloadPlatform "$platform"
            fi
          done

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build package
        run: swift build

      - name: Build for iOS (xcodebuild)
        run: |
          xcodebuild \
            -scheme RecipeApp \
            -destination 'generic/platform=iOS Simulator' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            build
