import Foundation
import SwiftData

@Model
final class ShoppingListItem {
    var quantity: Double
    var unit: String
    var isChecked: Bool
    var isAutoGenerated: Bool
    var addedAt: Date

    var ingredient: Ingredient?

    init(
        quantity: Double = 0,
        unit: String = "",
        isChecked: Bool = false,
        isAutoGenerated: Bool = false,
        ingredient: Ingredient? = nil
    ) {
        self.quantity = quantity
        self.unit = unit
        self.isChecked = isChecked
        self.isAutoGenerated = isAutoGenerated
        self.addedAt = Date()
        self.ingredient = ingredient
    }
}
