import Foundation
import SwiftData

@Model
final class ShoppingListItem {
    /// Shelf purchase quantity (snapped up to real retail sizes).
    var quantity: Double
    /// Shelf purchase unit (e.g. "lb", "carton", "jar").
    var unit: String
    /// Precise recipe-calculated quantity before shelf snap-up. Zero for manual items.
    var recipeQuantity: Double
    /// Precise recipe-calculated unit before shelf snap-up. Empty for manual items.
    var recipeUnit: String
    var isChecked: Bool
    var isAutoGenerated: Bool
    var addedAt: Date

    var ingredient: Ingredient?

    init(
        quantity: Double = 0,
        unit: String = "",
        recipeQuantity: Double = 0,
        recipeUnit: String = "",
        isChecked: Bool = false,
        isAutoGenerated: Bool = false,
        ingredient: Ingredient? = nil
    ) {
        self.quantity = quantity
        self.unit = unit
        self.recipeQuantity = recipeQuantity
        self.recipeUnit = recipeUnit
        self.isChecked = isChecked
        self.isAutoGenerated = isAutoGenerated
        self.addedAt = Date()
        self.ingredient = ingredient
    }
}
