import Foundation
import SwiftData

@MainActor
struct ShoppingListGenerator {
    private struct NeedKey: Hashable {
        let name: String
        let normalizedUnit: String
    }

    private struct NeededItem {
        let ingredient: Ingredient
        let unit: String
        var quantity: Double
    }

    static func generate(context: ModelContext, lookaheadDays: Int = 7) {
        // Clear existing auto-generated unchecked items
        let autoGenDescriptor = FetchDescriptor<ShoppingListItem>(
            predicate: #Predicate { $0.isAutoGenerated && !$0.isChecked }
        )
        if let existing = try? context.fetch(autoGenDescriptor) {
            for item in existing {
                context.delete(item)
            }
        }

        // Get upcoming meal plan entries
        let now = DateHelpers.startOfDay(Date())
        let endDate = DateHelpers.addDays(lookaheadDays, to: now)
        let entryDescriptor = FetchDescriptor<MealPlanEntry>(
            predicate: #Predicate {
                $0.date >= now && $0.date < endDate && $0.status == "planned"
            }
        )
        guard let entries = try? context.fetch(entryDescriptor) else { return }

        // Aggregate ingredient needs by canonical (ingredient name + normalized unit).
        var needed: [NeedKey: NeededItem] = [:]
        for entry in entries {
            guard let recipe = entry.recipe else { continue }
            let servingMultiplier =
                recipe.servings > 0 ? Double(entry.servings) / Double(recipe.servings) : 1.0
            for ri in recipe.recipeIngredients {
                guard let ingredient = ri.ingredient else { continue }
                let trimmedUnit = ri.unit.trimmingCharacters(in: .whitespacesAndNewlines)
                let normalizedUnit = UnitTextNormalizer.normalize(trimmedUnit)
                let key = NeedKey(name: ingredient.name, normalizedUnit: normalizedUnit)
                let qty = ri.quantity * servingMultiplier
                if var existingNeed = needed[key] {
                    existingNeed.quantity += qty
                    needed[key] = existingNeed
                } else {
                    needed[key] = NeededItem(
                        ingredient: ingredient,
                        unit: trimmedUnit.isEmpty ? normalizedUnit : trimmedUnit,
                        quantity: qty
                    )
                }
            }
        }

        // Subtract inventory using normalized unit matching.
        let inventoryDescriptor = FetchDescriptor<InventoryItem>()
        let inventory = (try? context.fetch(inventoryDescriptor)) ?? []
        var inventoryMap: [NeedKey: Double] = [:]
        for item in inventory {
            guard let ingredient = item.ingredient else { continue }
            let key = NeedKey(
                name: ingredient.name,
                normalizedUnit: UnitTextNormalizer.normalize(item.unit)
            )
            inventoryMap[key, default: 0] += item.quantity
        }

        let sortedNeeds = needed.values.sorted { lhs, rhs in
            let lhsCategoryRank = IngredientCategory.allCategories.firstIndex(of: lhs.ingredient.category) ?? Int.max
            let rhsCategoryRank = IngredientCategory.allCategories.firstIndex(of: rhs.ingredient.category) ?? Int.max
            if lhsCategoryRank != rhsCategoryRank {
                return lhsCategoryRank < rhsCategoryRank
            }

            let nameCompare = lhs.ingredient.displayName.localizedCaseInsensitiveCompare(rhs.ingredient.displayName)
            if nameCompare != .orderedSame {
                return nameCompare == .orderedAscending
            }

            let lhsUnit = UnitTextNormalizer.normalize(lhs.unit)
            let rhsUnit = UnitTextNormalizer.normalize(rhs.unit)
            let unitCompare = lhsUnit.localizedCaseInsensitiveCompare(rhsUnit)
            return unitCompare == .orderedAscending
        }

        // Create shopping list items in deterministic sorted order.
        for need in sortedNeeds {
            let inventoryKey = NeedKey(
                name: need.ingredient.name,
                normalizedUnit: UnitTextNormalizer.normalize(need.unit)
            )

            var toBuy = need.quantity
            if let onHand = inventoryMap[inventoryKey] {
                toBuy -= onHand
            }
            guard toBuy > 0 else { continue }

            let item = ShoppingListItem(
                quantity: toBuy,
                unit: need.unit,
                isAutoGenerated: true,
                ingredient: need.ingredient
            )
            context.insert(item)
        }

        try? context.save()
    }
}
