import Foundation
import SwiftData

@MainActor
struct ShoppingListGenerator {
    static func generate(context: ModelContext, lookaheadDays: Int = 7) {
        // Clear existing auto-generated unchecked items
        let autoGenDescriptor = FetchDescriptor<ShoppingListItem>(
            predicate: #Predicate { $0.isAutoGenerated && !$0.isChecked }
        )
        if let existing = try? context.fetch(autoGenDescriptor) {
            for item in existing {
                context.delete(item)
            }
        }

        // Get upcoming meal plan entries
        let now = DateHelpers.startOfDay(Date())
        let endDate = DateHelpers.addDays(lookaheadDays, to: now)
        let entryDescriptor = FetchDescriptor<MealPlanEntry>(
            predicate: #Predicate {
                $0.date >= now && $0.date < endDate && $0.status == "planned"
            }
        )
        guard let entries = try? context.fetch(entryDescriptor) else { return }

        // Aggregate ingredient needs
        var needed: [String: (quantity: Double, unit: String, ingredient: Ingredient)] = [:]
        for entry in entries {
            guard let recipe = entry.recipe else { continue }
            let servingMultiplier =
                recipe.servings > 0 ? Double(entry.servings) / Double(recipe.servings) : 1.0
            for ri in recipe.recipeIngredients {
                guard let ingredient = ri.ingredient else { continue }
                let key = ingredient.name
                let qty = ri.quantity * servingMultiplier
                if var existing = needed[key] {
                    existing.quantity += qty
                    needed[key] = existing
                } else {
                    needed[key] = (quantity: qty, unit: ri.unit, ingredient: ingredient)
                }
            }
        }

        // Subtract inventory
        let inventoryDescriptor = FetchDescriptor<InventoryItem>()
        let inventory = (try? context.fetch(inventoryDescriptor)) ?? []
        let inventoryMap = Dictionary(
            uniqueKeysWithValues: inventory.compactMap { item in
                item.ingredient.map { ($0.name, item.quantity) }
            }
        )

        // Create shopping list items
        for (key, need) in needed {
            let onHand = inventoryMap[key] ?? 0
            let toBuy = need.quantity - onHand
            guard toBuy > 0 else { continue }

            let item = ShoppingListItem(
                quantity: toBuy,
                unit: need.unit,
                isAutoGenerated: true,
                ingredient: need.ingredient
            )
            context.insert(item)
        }

        try? context.save()
    }
}
